name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./LineBotAI/LineBotAI.csproj

      - name: Build project
        run: dotnet build --configuration Release --no-restore
        working-directory: ./LineBotAI/LineBotAI.csproj

      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish --no-build
        working-directory: ./LineBotAI

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: linebotAI-Nora
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./LineBotAI/publish
